services:
  - type: web
    name: email-sender-api
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: RESEND_API_KEY
        sync: false
